apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5xc
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: f5xc
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "f5xc"   
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: f5xc-service-discovery
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - nodes/proxy
  - namespaces
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5xc-service-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: f5xc-service-discovery
subjects:
- kind: ServiceAccount
  name: f5xc
  namespace: kube-system
